config:
  backup: true
  create: true
  dotpath: dotfiles
dotfiles:
  d_widgets:
    dst: "~/Library/Application Support/\xDCbersicht/widgets"
    src: "Library/Application Support/\xDCbersicht/widgets"
  d_zprezto:
    dst: ~/.zprezto
    src: zprezto
  f_com.googlecode.iterm2.plist:
    dst: ~/Library/Preferences/com.googlecode.iterm2.plist
    src: Library/Preferences/com.googlecode.iterm2.plist
profiles:
  Eriks-MacBook-Pro.local:
    dotfiles:
    - d_zprezto
    - d_widgets
    - f_com.googlecode.iterm2.plist
