config:
  backup: true
  create: true
  dotpath: dotfiles
dotfiles:
  d_kwm:
    dst: ~/.kwm
    src: kwm
  d_widgets:
    dst: "~/Library/Application Support/\xDCbersicht/widgets"
    src: "Library/Application Support/\xDCbersicht/widgets"
  f_chunkwmrc:
    dst: ~/.chunkwmrc
    src: chunkwmrc
  f_com.googlecode.iterm2.plist:
    dst: ~/Library/Preferences/com.googlecode.iterm2.plist
    src: Library/Preferences/com.googlecode.iterm2.plist
  f_skhdrc:
    dst: ~/.skhdrc
    src: skhdrc
  f_zpreztorc:
    dst: ~/.zpreztorc
    src: zpreztorc
  f_zshrc:
    dst: ~/.zshrc
    src: zshrc
profiles:
  Eriks-MacBook-Pro.local:
    dotfiles:
    - d_widgets
    - f_com.googlecode.iterm2.plist
    - d_kwm
    - f_chunkwmrc
    - f_skhdrc
    - f_zpreztorc
  ITs-MacBook-Pro-8.local:
    dotfiles:
    - d_widgets
    - f_com.googlecode.iterm2.plist
    - d_kwm
    - f_chunkwmrc
    - f_skhdrc
    - f_zpreztorc
  ITs-MacBook-Pro-86.local:
    dotfiles:
    - f_zshrc
